#include "pch.h"
#include "MyPartialType_complete.h"

using namespace Platform;

namespace CppCx { namespace Partial {

void MyPartialType::InitializeChildNames ()
{
    m_childNames_AutoGenerated.emplace_back(ref new String(L"John-Boy"));
    m_childNames_AutoGenerated.emplace_back(ref new String(L"Jason"));
    m_childNames_AutoGenerated.emplace_back(ref new String(L"Mary Ellen"));
    m_childNames_AutoGenerated.emplace_back(ref new String(L"Erin"));
    m_childNames_AutoGenerated.emplace_back(ref new String(L"Ben"));
    m_childNames_AutoGenerated.emplace_back(ref new String(L"Jim-Bob"));
    m_childNames_AutoGenerated.emplace_back(ref new String(L"Elizabeth"));
}

} } // namespace CppCx::Partial
