#ifndef INCL_MYPARTIALTYPE_PARTIAL_H
#define INCL_MYPARTIALTYPE_PARTIAL_H

#include <vector>

partial ref class MyPartialType
{
private:
    void InitializeChildNames ();

    std::vector<Platform::String ^> m_childNames_AutoGenerated;
};

#endif // INCL_MYPARTIALTYPE_PARTIAL_H
