#ifndef INCL_MYPARTIALTYPE_PARTIAL_H
#define INCL_MYPARTIALTYPE_PARTIAL_H

#include <vector>

namespace CppCx { namespace Partial {

partial ref class MyPartialType
{
private:
    void InitializeChildNames ();

    std::vector<Platform::String ^> m_childNames_AutoGenerated;
};

} } // namespace CppCx::Partial

#endif // INCL_MYPARTIALTYPE_PARTIAL_H
